# NSE Sectoral Rotation Project
## — Running 12 SQL Queries

In [13]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(
    host="localhost",
    database="nse_analysis",
    user="postgres",
    password="postgres123"
)
print("✅ Connected!")

✅ Connected!

## Query 01 — Sector Annual Returns

In [14]:
q1 = open("../sql/query_01_sector_annual_returns.sql").read()
df_q1 = pd.read_sql(q1, conn)
df_q1

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\1280463930.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q1 = pd.read_sql(q1, conn)

     sector    year  annual_return_pct  rank
0   BANKING  2022.0              25.66     1
1      AUTO  2022.0              22.90     2
2    METALS  2022.0              11.28     3
3      FMCG  2022.0              10.10     4
4    ENERGY  2022.0               7.02     5
5   FINANCE  2022.0              -9.28     6
6    PHARMA  2022.0             -14.81     7
7        IT  2022.0             -33.34     8
8      AUTO  2023.0              45.27     1
9    PHARMA  2023.0              38.47     2
10       IT  2023.0              33.96     3
11   ENERGY  2023.0              33.75     4
12   METALS  2023.0              25.58     5
13     FMCG  2023.0              23.28     6
14  FINANCE  2023.0              19.45     7
15  BANKING  2023.0              12.63     8
16     AUTO  2024.0              56.75     1
17   METALS  2024.0              53.99     2
18   ENERGY  2024.0              45.86     3
19   PHARMA  2024.0              41.57     4
20  BANKING  2024.0              15.13     5
21     FMCG  2024.0              14.69     6
22  FINANCE  2024.0              14.27     7
23       IT  2024.0               2.44     8

## Query 02 — Sector vs NIFTY

In [15]:
q2 = open("../sql/query_02_sector_vs_nifty.sql").read()
df_q2 = pd.read_sql(q2, conn)
df_q2

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\965680034.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q2 = pd.read_sql(q2, conn)

     sector    year  sector_annual_return  nifty_annual_return  alpha
0   BANKING  2022.0                 23.19                 4.23  18.96
1      AUTO  2022.0                 21.14                 4.23  16.90
2      FMCG  2022.0                 10.28                 4.23   6.05
3    METALS  2022.0                  8.31                 4.23   4.08
4    ENERGY  2022.0                  6.03                 4.23   1.79
5   FINANCE  2022.0                -11.42                 4.23 -15.66
6    PHARMA  2022.0                -14.40                 4.23 -18.63
7        IT  2022.0                -34.10                 4.23 -38.33
8      AUTO  2023.0                 45.27                19.26  26.01
9    PHARMA  2023.0                 38.47                19.26  19.21
10       IT  2023.0                 33.96                19.26  14.70
11   ENERGY  2023.0                 33.75                19.26  14.49
12   METALS  2023.0                 25.58                19.26   6.32
13     FMCG  2023.0                 23.28                19.26   4.01
14  FINANCE  2023.0                 19.45                19.26   0.19
15  BANKING  2023.0                 12.63                19.26  -6.63
16     AUTO  2024.0                 56.75                23.91  32.84
17   METALS  2024.0                 53.99                23.91  30.08
18   ENERGY  2024.0                 45.86                23.91  21.95
19   PHARMA  2024.0                 41.57                23.91  17.66
20  BANKING  2024.0                 15.13                23.91  -8.78
21     FMCG  2024.0                 14.69                23.91  -9.22
22  FINANCE  2024.0                 14.27                23.91  -9.64
23       IT  2024.0                  2.44                23.91 -21.47

## Query 03 — Best and Worst Sectors Per Year

In [16]:
q3 = open("../sql/query_03_best_worst_sectors_per_year.sql").read()
df_q3 = pd.read_sql(q3, conn)
df_q3

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\623242284.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q3 = pd.read_sql(q3, conn)

     year best_sector  best_return worst_sector  worst_return
0  2022.0     BANKING        25.66           IT        -33.34
1  2023.0        AUTO        45.27      BANKING         12.63
2  2024.0        AUTO        56.75           IT          2.44

## Query 04 — Rotation Consistency

In [17]:
q4 = open("../sql/query_04_rotation_consistency.sql").read()
df_q4 = pd.read_sql(q4, conn)
df_q4

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\593427115.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q4 = pd.read_sql(q4, conn)

   sector  years_in_top3
0    AUTO              3
1  METALS              2

## Query 05 — Monthly Momentum

In [18]:
q5 = open("../sql/query_05_monthly_momentum.sql").read()
df_q5 = pd.read_sql(q5, conn)
df_q5

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\2457407852.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q5 = pd.read_sql(q5, conn)

     sector                     month  rolling_3month_return
0      AUTO 2021-12-31 18:30:00+00:00                  22.14
1      AUTO 2022-01-31 18:30:00+00:00                 -16.68
2      AUTO 2022-02-28 18:30:00+00:00                  -7.01
3      AUTO 2022-03-31 18:30:00+00:00                  20.34
4      AUTO 2022-04-30 18:30:00+00:00                  22.29
..      ...                       ...                    ...
243  PHARMA 2024-02-29 18:30:00+00:00                  -4.51
244  PHARMA 2024-03-31 18:30:00+00:00                   8.28
245  PHARMA 2024-04-30 18:30:00+00:00                   0.54
246  PHARMA 2024-05-31 18:30:00+00:00                  19.03
247  PHARMA 2024-06-30 18:30:00+00:00                  49.28

[248 rows x 3 columns]

## Query 06 — Sector Volatility

In [19]:
q6 = open("../sql/query_06_sector_volatility.sql").read()
df_q6 = pd.read_sql(q6, conn)
df_q6

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\305547372.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q6 = pd.read_sql(q6, conn)

     sector    year  volatility_pct
0    METALS  2022.0        212.3033
1        IT  2022.0        164.4210
2      AUTO  2022.0        145.7859
3   BANKING  2022.0        142.8932
4   FINANCE  2022.0        139.9196
5    ENERGY  2022.0        129.0243
6    PHARMA  2022.0        113.1464
7      FMCG  2022.0        106.4995
8    METALS  2023.0        119.5542
9        IT  2023.0        117.7452
10   ENERGY  2023.0        110.7337
11  FINANCE  2023.0        104.3620
12   PHARMA  2023.0         90.4975
13     AUTO  2023.0         85.5654
14  BANKING  2023.0         85.4338
15     FMCG  2023.0         67.6716
16   ENERGY  2024.0        218.1813
17   METALS  2024.0        201.6218
18       IT  2024.0        135.9439
19  BANKING  2024.0        131.9986
20  FINANCE  2024.0        117.0761
21     AUTO  2024.0        114.4308
22   PHARMA  2024.0        107.1063
23     FMCG  2024.0        103.0082

## Query 07 — Sharpe Proxy

In [20]:
q7 = open("../sql/query_07_sharpe_proxy.sql").read()
df_q7 = pd.read_sql(q7, conn)
df_q7

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\822459594.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q7 = pd.read_sql(q7, conn)

     sector    year  annual_return  volatility  sharpe_proxy
0   BANKING  2022.0          25.66    142.8932        0.1796
1      AUTO  2022.0          22.90    145.7859        0.1571
2      FMCG  2022.0          10.10    106.4995        0.0948
3    ENERGY  2022.0           7.02    129.0243        0.0544
4    METALS  2022.0          11.28    212.3033        0.0532
5   FINANCE  2022.0          -9.28    139.9196       -0.0663
6    PHARMA  2022.0         -14.81    113.1464       -0.1309
7        IT  2022.0         -33.34    164.4210       -0.2028
8      AUTO  2023.0          45.27     85.5654        0.5291
9    PHARMA  2023.0          38.47     90.4975        0.4251
10     FMCG  2023.0          23.28     67.6716        0.3440
11   ENERGY  2023.0          33.75    110.7337        0.3048
12       IT  2023.0          33.96    117.7452        0.2884
13   METALS  2023.0          25.58    119.5542        0.2140
14  FINANCE  2023.0          19.45    104.3620        0.1864
15  BANKING  2023.0          12.63     85.4338        0.1478
16     AUTO  2024.0          56.75    114.4308        0.4959
17   PHARMA  2024.0          41.57    107.1063        0.3882
18   METALS  2024.0          53.99    201.6218        0.2678
19   ENERGY  2024.0          45.86    218.1813        0.2102
20     FMCG  2024.0          14.69    103.0082        0.1426
21  FINANCE  2024.0          14.27    117.0761        0.1219
22  BANKING  2024.0          15.13    131.9986        0.1147
23       IT  2024.0           2.44    135.9439        0.0179

## Query 08 — Top Stocks Per Sector

In [21]:
q8 = open("../sql/query_08_top_stocks_per_sector.sql").read()
df_q8 = pd.read_sql(q8, conn)
df_q8

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\644740696.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q8 = pd.read_sql(q8, conn)

     sector    year     symbol  annual_return  rank
0      AUTO  2022.0   TVSMOTOR          60.44     1
1      AUTO  2022.0        M&M          44.80     2
2      AUTO  2022.0  EICHERMOT          26.80     3
3      AUTO  2022.0   ASHOKLEY          21.85     4
4      AUTO  2022.0     MARUTI          16.47     5
..      ...     ...        ...            ...   ...
115  PHARMA  2024.0     BIOCON          87.87     1
116  PHARMA  2024.0      LUPIN          63.00     2
117  PHARMA  2024.0  SUNPHARMA          49.03     3
118  PHARMA  2024.0      CIPLA          41.73     4
119  PHARMA  2024.0   DIVISLAB          37.02     5

[120 rows x 5 columns]

## Query 09 — Drawdown Analysis

In [22]:
q9 = open("../sql/query_09_drawdown_analysis.sql").read()
df_q9 = pd.read_sql(q9, conn)
df_q9

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\1358506554.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q9 = pd.read_sql(q9, conn)

     sector    year  max_drawdown_pct
0        IT  2022.0          -4237.91
1    METALS  2022.0          -4202.66
2   FINANCE  2022.0          -2988.18
3    ENERGY  2022.0          -2812.22
4      AUTO  2022.0          -2158.02
5    PHARMA  2022.0          -1854.41
6   BANKING  2022.0          -1691.51
7      FMCG  2022.0          -1322.01
8    ENERGY  2023.0          -1889.20
9   FINANCE  2023.0          -1798.64
10   METALS  2023.0          -1554.95
11       IT  2023.0          -1476.34
12  BANKING  2023.0          -1206.10
13     AUTO  2023.0          -1056.34
14   PHARMA  2023.0           -985.18
15     FMCG  2023.0           -516.05
16       IT  2024.0          -2492.12
17   ENERGY  2024.0          -1420.81
18   METALS  2024.0          -1217.84
19  FINANCE  2024.0          -1140.82
20  BANKING  2024.0           -874.01
21     FMCG  2024.0           -697.03
22   PHARMA  2024.0           -691.13
23     AUTO  2024.0           -465.74

## Query 10 — Correlation Matrix

In [23]:
q10 = open("../sql/query_10_correlation_matrix.sql").read()
df_q10 = pd.read_sql(q10, conn)
df_q10

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\1199263387.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q10 = pd.read_sql(q10, conn)

   sector_1 sector_2  correlation
0   BANKING  FINANCE       0.6343
1    ENERGY   METALS       0.6337
2      AUTO  BANKING       0.6311
3      AUTO  FINANCE       0.5709
4   BANKING   METALS       0.5418
5   BANKING   ENERGY       0.5238
6      AUTO   ENERGY       0.4760
7      AUTO     FMCG       0.4693
8   FINANCE     FMCG       0.4672
9   FINANCE   METALS       0.4588
10     AUTO   METALS       0.4529
11     FMCG   PHARMA       0.4268
12  FINANCE   PHARMA       0.4243
13  FINANCE       IT       0.4230
14     AUTO   PHARMA       0.4198
15       IT   PHARMA       0.4157
16   ENERGY  FINANCE       0.4146
17   METALS   PHARMA       0.4117
18       IT   METALS       0.4029
19  BANKING     FMCG       0.3811
20  BANKING       IT       0.3797
21  BANKING   PHARMA       0.3628
22     AUTO       IT       0.3511
23   ENERGY   PHARMA       0.3144
24     FMCG       IT       0.3097
25   ENERGY       IT       0.2691
26     FMCG   METALS       0.2334
27   ENERGY     FMCG       0.2074

## Query 11 — Volume Trend

In [24]:
q11 = open("../sql/query_11_volume_trend.sql").read()
df_q11 = pd.read_sql(q11, conn)
df_q11

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\660340013.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q11 = pd.read_sql(q11, conn)

     sector    year  avg_daily_volume
0    METALS  2022.0        16352613.0
1    ENERGY  2022.0        10956242.0
2   BANKING  2022.0         9560563.0
3      AUTO  2022.0         5039114.0
4      FMCG  2022.0         3014358.0
5        IT  2022.0         2954611.0
6   FINANCE  2022.0         1571371.0
7    PHARMA  2022.0         1471110.0
8    METALS  2023.0        14108974.0
9   BANKING  2023.0        11174871.0
10   ENERGY  2023.0        10168710.0
11     AUTO  2023.0         3684418.0
12       IT  2023.0         2287852.0
13     FMCG  2023.0         2243444.0
14  FINANCE  2023.0         1714523.0
15   PHARMA  2023.0         1532868.0
16   METALS  2024.0        22758873.0
17   ENERGY  2024.0        16954966.0
18  BANKING  2024.0        14134961.0
19     AUTO  2024.0         4546770.0
20     FMCG  2024.0         3445611.0
21       IT  2024.0         3005497.0
22   PHARMA  2024.0         2205154.0
23  FINANCE  2024.0         2091176.0

## Query 12 — 52 Week High Low

In [25]:
q12 = open("../sql/query_12_52week_high_low.sql").read()
df_q12 = pd.read_sql(q12, conn)
df_q12

C:\Users\balap\AppData\Local\Temp\ipykernel_30856\424271830.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_q12 = pd.read_sql(q12, conn)

     sector    year  near_52w_high  near_52w_low
0      AUTO  2022.0           1116           999
1   BANKING  2022.0           1586           529
2    ENERGY  2022.0            996          1118
3   FINANCE  2022.0            523          1050
4      FMCG  2022.0           1393           810
5        IT  2022.0            749          1435
6    METALS  2022.0            956           577
7    PHARMA  2022.0            739          1347
8      AUTO  2023.0           1892           135
9   BANKING  2023.0           1855           203
10   ENERGY  2023.0           1844           168
11  FINANCE  2023.0           1248           319
12     FMCG  2023.0           1840           250
13       IT  2023.0           2167            96
14   METALS  2023.0           1323           157
15   PHARMA  2023.0           1865           179
16     AUTO  2024.0            867           213
17  BANKING  2024.0            835           198
18   ENERGY  2024.0            756           268
19  FINANCE  2024.0            608           233
20     FMCG  2024.0            914           203
21       IT  2024.0            866           334
22   METALS  2024.0            701            73
23   PHARMA  2024.0            926           112

## Close the connection